server:
  port: 7001
spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowed-origin-patterns: "http://*"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true # 允许携带 cookie
            max-age: 3600 # 一次跨域允许请求的事件为 3600s
      discovery:
        locator:
          enabled: true
      routes:
        - id: student-service
          uri: lb://student-service
          predicates:
            - Path=/student/**
          filters:
            - StripPrefix=1
        - id: teacher-service
          uri: lb://teacher-service
          predicates:
            - Path=/teacher/**
          filters:
            - StripPrefix=1
        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/admin/**
          filters:
            - StripPrefix=1
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1